# Generated by Django 4.0.3 on 2022-03-23 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=64, verbose_name='Название категории')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='images/categories/% Y/% m/% d/', verbose_name='Изображение категории')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название компании', max_length=64, verbose_name='Название компании')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(help_text='Введите дату заказа', verbose_name='Дата заказа')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['order_date'],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, help_text='Введите отчество', max_length=64, null=True, verbose_name='Отчество')),
                ('telephone', models.CharField(blank=True, help_text='Введите номер телефона', max_length=11, null=True, verbose_name='Номер телефон')),
                ('date_of_birth', models.DateField(blank=True, help_text='Введите дату рождения', null=True, verbose_name='Дата рождения')),
                ('country', models.CharField(blank=True, help_text='Введите страну', max_length=64, null=True, verbose_name='Страна')),
                ('region', models.CharField(blank=True, help_text='Введите регион', max_length=64, null=True, verbose_name='Регион')),
                ('city', models.CharField(blank=True, help_text='Введите город', max_length=64, null=True, verbose_name='Город')),
                ('address', models.CharField(blank=True, help_text='Введите адрес', max_length=64, null=True, verbose_name='Адрес')),
                ('avatar', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='images/avatars/% Y/% m/% d/', verbose_name='Аватар пользователя')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название продукта', max_length=64, verbose_name='Название продукта')),
                ('price', models.DecimalField(decimal_places=4, help_text='Введите цену', max_digits=15, verbose_name='Цена продукта')),
                ('description', models.TextField(help_text='Введите описание', verbose_name='Описание продукта')),
                ('quantity', models.PositiveIntegerField(help_text='Введите количество продукта', verbose_name='Описание продукта')),
                ('categories', models.ManyToManyField(help_text='Выберите категорию', to='store.category', verbose_name='Категория')),
                ('manufacture', models.ForeignKey(help_text='Выберите компанию', on_delete=django.db.models.deletion.CASCADE, to='store.manufacture', verbose_name='Компания')),
            ],
            options={
                'ordering': ['price', 'quantity'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Введите количество товара', verbose_name='Количество товара')),
                ('order', models.ForeignKey(help_text='Выберите заказ', on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(help_text='Выберите продукт', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Введите название опции', verbose_name='Название опции')),
                ('description', models.TextField(help_text='Введите описание опции', verbose_name='Описание опции')),
                ('product', models.ForeignKey(help_text='Выберите продукт', on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите изображение продукта', upload_to='images/products/% Y/% m/% d/', verbose_name='Изображение продукта')),
                ('product', models.ForeignKey(help_text='Выберите продукт', on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Введите процент скидки', max_digits=10, verbose_name='Процент скидки')),
                ('date_start', models.DateField(help_text='Введите дату начала акции', verbose_name='Дата начала акции')),
                ('date_end', models.DateField(help_text='Введите дата окончания акции', verbose_name='Дата окончания акции')),
                ('product', models.ForeignKey(help_text='Выберите продукт', on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Продукт')),
            ],
            options={
                'ordering': ['-date_end'],
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Введите название характеристики', verbose_name='Название категории')),
                ('description', models.TextField(help_text='Введите описание характеристики', verbose_name='Описание характеристики')),
                ('product', models.ForeignKey(help_text='Выберите продукт', on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Введите количество бонусов', verbose_name='Количество бонусов')),
                ('date_start', models.DateField(help_text='Введите дату начала', verbose_name='Дата начала')),
                ('date_end', models.DateField(help_text='Введите дату окончания', verbose_name='Дата окончания')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['date_end'],
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Товар')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
