# Generated by Django 4.0.3 on 2022-11-16 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=64, verbose_name='Название категории')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='images/categories/%Y/%m/%d/', verbose_name='Изображение категории')),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название компании', max_length=64, verbose_name='Название компании')),
            ],
            options={
                'verbose_name_plural': 'Производитель',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название опции', max_length=64, verbose_name='Название опции')),
            ],
            options={
                'verbose_name_plural': 'Опции',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(help_text='Введите дату заказа', verbose_name='Дата заказа')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Заказы пользователей',
                'ordering': ['order_date'],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, help_text='Введите отчество', max_length=64, null=True, verbose_name='Отчество')),
                ('telephone', models.CharField(blank=True, help_text='Введите номер телефона', max_length=11, null=True, verbose_name='Номер телефон')),
                ('date_of_birth', models.DateField(blank=True, help_text='Введите дату рождения', null=True, verbose_name='Дата рождения')),
                ('country', models.CharField(blank=True, help_text='Введите страну', max_length=64, null=True, verbose_name='Страна')),
                ('region', models.CharField(blank=True, help_text='Введите регион', max_length=64, null=True, verbose_name='Регион')),
                ('city', models.CharField(blank=True, help_text='Введите город', max_length=64, null=True, verbose_name='Город')),
                ('address', models.CharField(blank=True, help_text='Введите адрес', max_length=64, null=True, verbose_name='Адрес')),
                ('avatar', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='images/avatars/%Y/%m/%d/', verbose_name='Аватар пользователя')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название подкатегории', max_length=64, verbose_name='Название подкатегории')),
                ('category', models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='store.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Подкатегории',
                'db_table': 'store_subcategory_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название продукта', max_length=64, verbose_name='Название продукта')),
                ('price', models.DecimalField(decimal_places=4, help_text='Введите цену', max_digits=15, verbose_name='Цена продукта')),
                ('description', models.TextField(help_text='Введите описание', verbose_name='Описание продукта')),
                ('quantity', models.PositiveIntegerField(help_text='Введите количество продукта', verbose_name='Количество продукта')),
                ('isRecommended', models.BooleanField(default=False, help_text='Добавить товар в рекомендованные?', verbose_name='Рекомендовать')),
                ('category', models.ForeignKey(help_text='Выберите категории', on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категории')),
                ('manufacture', models.ForeignKey(help_text='Выберите компанию', on_delete=django.db.models.deletion.CASCADE, to='store.manufacture', verbose_name='Компания')),
                ('option', models.ManyToManyField(help_text='Выберите опции', to='store.option', verbose_name='Опции')),
                ('subcategory', models.ManyToManyField(help_text='Выберите подкатегории', to='store.subcategory', verbose_name='Подкатегории')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'ordering': ['name', 'price', 'quantity'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Введите количество товара', verbose_name='Количество товара')),
                ('old_price', models.DecimalField(decimal_places=4, help_text='Введите цену', max_digits=15, verbose_name='Старая цена продукта')),
                ('order', models.ForeignKey(help_text='Выберите заказ', on_delete=django.db.models.deletion.CASCADE, related_name='products_in_order', to='store.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(help_text='Выберите продукт', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name_plural': 'Информация о заказе',
                'db_table': 'store_order_product',
            },
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Введите значение опции', max_length=64, verbose_name='Значение опции')),
                ('option', models.ForeignKey(help_text='Выберите опцию', on_delete=django.db.models.deletion.CASCADE, to='store.option', verbose_name='Опция')),
            ],
            options={
                'verbose_name_plural': 'Значения опций',
                'db_table': 'store_option_value',
            },
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите изображение продукта', upload_to='images/products/%Y/%m/%d/', verbose_name='Изображение продукта')),
                ('product', models.ForeignKey(help_text='Выберите продукт', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name_plural': 'Изображения продуктов',
                'db_table': 'store_image_product',
            },
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Избранный товар')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Избранные товары пользователей',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Введите процент скидки', max_digits=10, verbose_name='Процент скидки')),
                ('date_start', models.DateField(help_text='Введите дату начала акции', verbose_name='Дата начала акции')),
                ('date_end', models.DateField(help_text='Введите дата окончания акции', verbose_name='Дата окончания акции')),
                ('product', models.ForeignKey(help_text='Выберите продукт', on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='store.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name_plural': 'Скидки',
                'ordering': ['-date_end'],
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Введите название характеристики', verbose_name='Название характеристики')),
                ('description', models.TextField(help_text='Введите описание характеристики', verbose_name='Описание характеристики')),
                ('product', models.ForeignKey(help_text='Выберите продукт', on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Введите количество бонусов', verbose_name='Количество бонусов')),
                ('date_start', models.DateField(help_text='Введите дату начала', verbose_name='Дата начала')),
                ('date_end', models.DateField(help_text='Введите дату окончания', verbose_name='Дата окончания')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Бонусы',
                'ordering': ['date_end'],
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(help_text='Выберите товар', to='store.product', verbose_name='Товар')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Корзины пользователей',
            },
        ),
    ]
