# Generated by Django 4.0.3 on 2022-03-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imageproduct',
            table='store_image_product',
        ),
        migrations.AlterModelTable(
            name='orderproduct',
            table='store_order_product',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='user_info',
        ),
    ]
