# Generated by Django 4.0.3 on 2022-05-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(blank=True, help_text='Загрузите изображение продукта', to='store.imageproduct', verbose_name='Изображение продукта'),
        ),
    ]
