# Generated by Django 4.0.3 on 2022-03-31 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_image_alter_imageproduct_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='description',
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(help_text='Введите название опции', max_length=64, verbose_name='Название опции'),
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Введите значение опции', max_length=64, verbose_name='Значение опции')),
                ('option', models.ForeignKey(help_text='Выберите опцию', on_delete=django.db.models.deletion.CASCADE, to='store.option', verbose_name='Опция')),
            ],
            options={
                'db_table': 'store_option_value',
            },
        ),
    ]
