# Generated by Django 4.0.3 on 2022-03-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_option_description_alter_option_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(help_text='Выберите опции', to='store.option', verbose_name='Опции'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(help_text='Выберите категории', to='store.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Введите количество продукта', verbose_name='Количество продукта'),
        ),
    ]
