# Generated by Django 4.0.3 on 2022-04-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_option_product_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['date_end'], 'verbose_name_plural': 'Bonus'},
        ),
    ]
