# Generated by Django 4.0.3 on 2022-04-20 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_bonus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name_plural': 'Корзины пользователей'},
        ),
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['date_end'], 'verbose_name_plural': 'Бонусы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-date_end'], 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='imageproduct',
            options={'verbose_name_plural': 'Изображения продуктов'},
        ),
        migrations.AlterModelOptions(
            name='manufacture',
            options={'verbose_name_plural': 'Производитель'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name_plural': 'Опции'},
        ),
        migrations.AlterModelOptions(
            name='optionvalue',
            options={'verbose_name_plural': 'Значения опций'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['order_date'], 'verbose_name_plural': 'Заказы пользователей'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name_plural': 'Информация о заказе'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price', 'quantity'], 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': 'Пользователи'},
        ),
    ]
