# Generated by Django 4.0.3 on 2022-10-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_basket_options_alter_bonus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isRecomendet',
            field=models.BooleanField(default=False, help_text='Рекомендовать товар?', verbose_name='da'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='product',
            field=models.ForeignKey(help_text='Выберите продукт', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Продукт'),
        ),
    ]
