# Generated by Django 4.0.3 on 2022-05-18 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0007_alter_basket_options_alter_bonus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ManyToManyField(help_text='Выберите скидку', to='store.discount', verbose_name='Скидка'),
        ),
    ]
