# Generated by Django 4.0.3 on 2022-10-27 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_isrecomendet_alter_imageproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isRecomendet',
        ),
        migrations.AddField(
            model_name='product',
            name='isRecommended',
            field=models.BooleanField(default=False, help_text='Добавить товар в рекомендованные?', verbose_name='Рекомендовать'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(default=1, help_text='Выберите категории', on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категории'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название подкатегории', max_length=64, verbose_name='Название подкатегории')),
                ('category', models.ForeignKey(help_text='Выберите Категорию', on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ManyToManyField(help_text='Выберите подкатегории', to='store.subcategory', verbose_name='Подкатегории'),
        ),
    ]
