# Generated by Django 4.0.3 on 2022-05-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_favourites'),
        ('store', '0008_remove_discount_product_product_discount_favourites'),
    ]

    operations = [
    ]
