# Generated by Django 4.0.3 on 2022-05-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_merge_20220518_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(help_text='Выберите категории', null=True, to='store.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ManyToManyField(help_text='Выберите скидку', null=True, to='store.discount', verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(help_text='Выберите опции', null=True, to='store.option', verbose_name='Опции'),
        ),
    ]
