# Generated by Django 4.0.3 on 2022-10-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_isrecomendet_product_isrecommended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='name',
            field=models.TextField(help_text='Введите название характеристики', verbose_name='Название характеристики'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(help_text='Выберите категории', to='store.category', verbose_name='Категории'),
        ),
    ]
