# Generated by Django 4.0.3 on 2022-10-27 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_characteristic_name_remove_product_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='options',
            new_name='option',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ForeignKey(default=1, help_text='Выберите Подкатегорию', on_delete=django.db.models.deletion.CASCADE, to='store.subcategory', verbose_name='Подкатегория'),
            preserve_default=False,
        ),
    ]
