# Generated by Django 4.0.3 on 2022-05-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_characteristic_name_alter_product_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Выберите категории', to='store.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ManyToManyField(blank=True, help_text='Выберите скидку', to='store.discount', verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, help_text='Выберите опции', to='store.option', verbose_name='Опции'),
        ),
    ]
