# Generated by Django 4.0.3 on 2022-10-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_categories_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(default=2, help_text='Выберите категории', on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=2, help_text='Выберите Подкатегорию', on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Подкатегория'),
            preserve_default=False,
        ),
    ]
