# Generated by Django 4.0.3 on 2022-05-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_is_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_recommended',
            field=models.BooleanField(blank=True, default=False, help_text='Рекомендовать этот продукт', null=True, verbose_name='Рекомендовать?'),
        ),
    ]
