# Generated by Django 4.0.3 on 2022-10-27 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_categories_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price', 'quantity'], 'verbose_name_plural': 'Товары'},
        ),
    ]
